### PR TITLE
Use the comment syntax for the Source URL

### PR DESCRIPTION
**Pull request by clin1234**

### CODE REVIEW

**Comment by hieunc229** [comment]
Thanks for the PR, Charlie. I forgot to let you know I've already fixed the issue in the earlier push changes https://github.com/hieunc229/copilot-clone/commit/6551eb2710d1b57b19c55aeebe2ef4f98998f8e8

We'll not be working with Github Actions at the moment (as discussed in this thread https://github.com/hieunc229/copilot-clone/pull/17). Besides, to make it easier to manage and looking back in the future, it's a good practice to keep a single problem in a single PR. _(This PR have both about Github Actions and the regex problem)_

**Comment by clin1234** [comment]
Correct me if I'm wrong, but characters in a square brackets do not get captured when `exec()` gets called. Thus `exec()` checks if the input string for these characters, but disregards them after the search phrase is captured. My pull request changes the square brackets into capturing round brackets in order to embed the correct line comment for the current language when outputting the source SO link.

**Comment by hieunc229** [comment]
Ah, I get what you mean there.

**Comment by hieunc229** [comment]
I made some changes, wanted to commit to this PR but accidentally commit to the master branch (tested a few cases)

What changed was:
1. Your idea of capturing the comment syntax and use it for the Source URL. I also update the regex pattern to capture the comment closing syntax (some languages like HTML need the closing comment `-->`)
2. Move the `matchPhrase` to its own file `/utils/matchSearchPhrase.ts` to make it easier to manage

Nice idea, Charlie 👍. The changes are here if you want to have a look https://github.com/hieunc229/copilot-clone/commit/03466b299aec371060c25a43c8586e5a8e81309b. You can test it by pulling the latest version of the `master` branch

**Pull request merged**
