### PR TITLE
Replace search phrase start/end with regex

### PR DESCRIPTION
**Pull request by hieunc229**
I've updated how to handle search phrases to avoid using `//` (comment annotation in JS) in different languages.

What changed? `SEARCH_START_PHRASE` and `SEARCH_END_PHRASE` were replaced with a regex pattern. It will match with anything in between `//find` and `.`  (a dot)

---

For example, to match the phrase "regex validate email"

With HTML, the syntax can be:
```html
<!-- //find regex validate email. -->
```

With Python, the syntax can be:
```python
# //find regex validate email.
```

With JavaScript, the syntax can be:
```js
//find regex validate email.
```

and so on...

---

I tested with VSCode Insider and it works as expected. The syntax seems unpleasant for some languages, but not too much hassle and easy to implement

@clin1234 @Kek5chen  What do you think about this?

### CODE REVIEW

**Comment by Kek5chen** [comment]
I dont like how you have to comment it twice... We should just hard code the comment types in. Or we make a global keyword for captain spark instead of //find. I'd say its better than before as you dont have to put the uncommented invalid code in your file, but still not very user friendly.

**Comment by hieunc229** [comment]
Great idea. What I like about using `//find` is it's easy to remember.

What should we use? 
- `stackfind` 
- `stfind`
- your suggestion?

**Comment by clin1234** [comment]
Suggestion: 
```typescript
const CSConfig = {
    SEARCH_ENDPOINT: `https://www.google.com/search?q=site%3Astackoverflow.com+`,
    SEARCH_PATTERN: /^(\/\/|#|!|--)find\s?(.+)\.$/
};
```

**Comment by hieunc229** [comment]
@clin1234 looks good (the pattern needs to change a bit for the HTML tag `<!--`)

By the way, I've just had a look at [Comment (computer language) on Wikipeadia](https://en.wikipedia.org/wiki/Comment_(computer_programming)) and there are more variations (i.e `/*`, `<#`, ...).

Seems like using a keyword as @Kek5chen suggest would be best

**Comment by clin1234** [comment]
My suggestion only holds for single-line comments (and because Google queries are limited to around 32 words)

**Comment by hieunc229** [comment]
You're right. It covers the single-line comment for most languages.

One suggestion is the pattern doesn't have to use the start with (`^`) and end with the end (`$`) expression. In case there are space indentations

**Comment by Kek5chen** [comment]
I checked the regex. I made it to this which works pretty good `^(\/\/|#|!|--|<!--) *find\s?(.+)\.$`

This lets both "!find hey." and "! find hey." work. This might be more comfortable looking in some programming languages.

**Review by Kek5chen — COMMENTED** [review]
The regex is too underdeveloped. Changing it to something around as said [here](https://github.com/hieunc229/copilot-clone/pull/16#issuecomment-887614653) would be appreciated. Otherwise it looks pretty good.

**Comment by hieunc229** [comment]
If we use the comment syntax, having space between the comment syntax and the word `find` will be an issue (when someone wants to comment instead of trigger inline completion, i.e `// find the index of the given letter.`)

**Comment by Kek5chen** [comment]
well but some programming languages prefer using no spaces too. so both would be a problem, using the spaces would at least add a little bit of variety. and if the user didnt want the inline completion to trigger they shall just press cancel.

**Comment by hieunc229** [comment]
Alright, will use it as discussed above. We can always come back if more people complain.

I'll update the regex as `/(\/\/|#|--|<!--)\s?find\s?(.+)\./` 

- no start/end with syntax (in case of space indentation)
- optional space before and after `find`
- match with most languages

**Review by Kek5chen — APPROVED** [review]

**Pull request merged**
