### PR TITLE
Update to v0.0.5

### LINKED ISSUE #62: Port From Insider To Stable VS Code
The proposed API for inline completions has now been released.

See this:
https://github.com/microsoft/vscode-discussions/discussions/26

### PR DESCRIPTION
**Pull request by hieunc229**
Changes:
- Readme: added Captain Stack link on Marketplace, update install instruction
- Minor code improvement and clean up

### CODE REVIEW

**Comment by hieunc229** [comment]
Hey @Kek5chen, please ignore the CI failing checks (probably need to remove it from the repo soon).

After this PR is reviewed, I'll upload this version into the marketplace

**Comment by Kek5chen** [comment]
do not ignore package-lock.json. i've said it before.

**Comment by Kek5chen** [comment]
I put in the continuous integration checks myself. we do not have to remove them. they work. they exist for exactly this reason.

**Review by Kek5chen — APPROVED** [review]
works, checks also passed. approved. good job.

**Comment by hieunc229** [comment]
I must have missed the information somewhere (the package-lock and CI integration), though will remember it.
Thanks for reviewing @Kek5chen.

**Pull request merged**
