### PR TITLE
Added AI Code Validation

### PR DESCRIPTION
**Pull request by Kek5chen**
AI to validate code snippets. I had good results testing this. Text gets filtered out pretty much all the time.

Here are some test results:
```
testing: abc
false

testing: abbbbc                         
false                                   

testing: a();                           
true                                    

testing: hello bbs ((((                 
false                                   

testing: this could be code()           
found keyword: this                     
true                                    

testing: <html stuff="blep">abc</html>  
true                                    

testing: for(var i = 0; i < 10; i++) { }
true                                    

testing: while i make cheese, i eat it  
found keyword: while                    
false                                   

testing: if (i == 0) { }                
found keyword: if                       
true                                    

testing: if (i == 0) { } else { }       
found keyword: if                       
found keyword: else                     
true                                    

testing: lorem ipsum dolor sit amet
false
```

### CODE REVIEW

**Comment by Kek5chen** [comment]
Code hasn't been integration tested. Unit tests succeeded with high confidence. Please run and see if everything works as expected.

**Comment by hieunc229** [comment]
Good idea @Kek5chen. Sorry I've been away for some time. I'll test it out this week!

**Comment by hieunc229** [comment]
Hey @Kek5chen, I tried to test the code. It works well with code that has a large amount. Though, not work in some cases, i.e simple code (which are unlikely to be a StackOverflow answer)

I used the following code to test (the link is actually long)

https://www.typescriptlang.org/play?#code/MYewdgzgLgBA1gUwJ4HcQCcAmEYF4YDaARJggGZEA0MRAbiAJaZU0NhQtEMXVEIA2EBJxQALBv2G90CKAFd0YTlHRypNMgENB6omDn9+y8RCIBdANwAoKwHpbMAMKiEwODDGyX6GFBcw2AAc5WAhREANMGAAjBBhQSCYEGSjNHFBSALBg2AwYdE0wTBAAW18EAA8oKzI5MGAoBnAAiEcQUgA1bSYACiCQgC4YaHQ2AHMASiHokBBJQpgAbysYVfjwaBgQQIQwAEEwMck8LJyAOghA-gYoHoByAB47ibPJQ78YAFoYAEZrNfWkFgwH4ICEmAORzi+H6UAuVxu9wAfM9Xrsxh9vn8bACEpttrsAEIFNyyHAw7IheHXW53Aiot4Y0RfX7-NZ44Gg8HEzSkqDk05Uy40+5mBnozGsnHsja5HZgRwKfhIE6w6mIu6LcXvZlYtmrDnxLkITCK9DK1WUuHCjUAX21TJZ2JWMqBW3lAAVNDIwJbzjbafcXozJdjcbKjWCTV6fX6hQjaRMHaHrC6DRGoCAoNoTgT9odjgBqSPgyFF91EkmIfkwYsgqOYHl8nDFvNmi1142mpUq1ue727Wsl6MDsCp8NutgIACOcm6UBV+E+AFlNH4zppohAenmy3FvvXSwWEBMvmmATBV+vN9u803qzgD1372TT59zwCr6IN1ud-L2yqT4NgBb4fmsX4-re-axkB4IxrsEzjq6mxCCUDCgKCkBxtaCb3BYya6lKE6bBhGzYeqtIDARTpIaskiwIgqAYNgABiERFCcAAMtGCjhIp3DAqIQKUCA9GgWB4EiSxgas3AwD0jHidgZxsCCcikNuSkTKeywXnp8DIEpEBsXUmCFoW+r6asMjyIoviqAglkAraMn5LICi+loOiWbaiHSnRsiAmQST1NCMDceeCTBaQoW1vgmbZvwMBSZxMAAPwwGcACsMBDJ82WWVFIXAHEhYUucIbMlJABs6WZTleVnGGrrRbsJVxVkM5zjSKoPOFdVTrO84qg4PypUMCU5rg+CpRl42ZbVABUvhZjmDgAEyFeArWxWVwwIGhpFYSldXZblXwFZF23FaV+BHTgJ0ZWc63nflm1XWAO3tXtinMcZ7FRI9mUAOznRF542R5QU3cl+DYi5ViGrCEBDAQIzjNQMxzAghRmAQZgnAQ-kwPYMAAEqFMUZTo4c54EAABoIIDJJg9PUF5QhmJQxOkwAUpotCaAAysAoyBNUAIM7U9SNM0PQ6TAtps-ZahczzDgAKpkwAMnT9NjLMUJnKAJTKxzCBq+efMC8LosMOLeuCz4FQnAALBYysqKr3NWw4-OCyLYsS2sDOGrAcMAJwe9QXsWz7AKkx6SB+OAeuaGMYVjZ7DmWwnfs2xAdsO5L9OBKM7A9EQLiGCAHgYPwzATNn3vqzA-tpEXsA9LUhjrKQEx69LDRNL6wDaMABhrqJsITMsaZOzAZAnIsMCaJgURDHchZ3DJ1AQHI0TnXcnwCbvMCYAwtBH7YO-6dQJT8LAm+Lbfen3+0R8AKSvxe1CVIER8AB6AlbS0VJo4GQU9V7oAKCqMgeQADyWBkhbCXggnYBRZa+kpjAMurgTRtQQGmMgZxZi13wAQAghASEPygATagBASEX1oPQ6hZwSjtFYYws4-8CZqyslQ7ha9MBcJIfvaIfDLD+VhORGQVxeSiVsAQQBnFPgR0-oAxaAAdWw8stGfELGcMwtgxiUDuM8CwVk1ikxBDjX0cgAF1DAPgiAEBvQqmAKIb0vIoDJAgP5BeEQoA5H1PA9APQF4MFwJxagYBcAkLIWiHUliGAPDHAEcyMBZ7SlJmTBAYxJ4+AAKIVDwa4keK0YCghAO4MJFZMEYBwLEKAKAECDjIKCNc4wYD6BKLEdAOA8hsF8RnAZLoF4yBOM4lA5N8klMCPcHoWitFmWWWcNKyzMCLQmD0Agyyt4JNmAQBgZgzgACtGBgHuPsiY28zA7M2YWNZGyVnbIsS6GQrw0hQAAJJFEqFxSxVjgUgr0qTWI8RNAhCaHIHAOCZBCFgJM6A3pYCBDBDkhw2tZgALEBIOIfhkhxAYDgaAEgkpj34BPfgXTmh1MkLQAQqDcEyBKjFEqLo8WSB6G5M4vjoB9CtKebJF57DFAniUXYcIUCjF8fcB4zCURDhkcWR4thFXvIvEEnIJxKXAAAPrDOSGAbQPQ8ljHmWcAAJD8Sg5rLVWvWnauZpTrUAGY-IXjkn0CAAA5TQvqdwhByKeAAPqGmAABCElLE2A3FEtqkI2k3K2V9ImqAQKSYOEqDcGAONzQqjkmALMq8elyD6ckD8MjZEIHkSVHoMhKDps9YrNMCM1iQzsum2iQ8sGQqpYa9gxrTWaCbYESg0QRWr1wJoRafwYi4GiHOtkEAUA3E8X+Kd7I0hxBIcIoYnbsGFmiJY6IkC4BOTHkIReFwD4HvcnZTQnwT0xHPZendN7mH3tTavWwL6z04wvR+K9u72GP2-VDWd-633AY-TQ9oEHH2f2g4B9916SH-0Q76CC6KUA9FHZO09MGLykC0AYKAQx9CGDZC5NYLklYxxzvHaxDgAASAAVZcusS4PGiEiVjAhQQwAAOoIJ1gAEQeH+pEzc46t0cELIWeszgzBdivFwDAxiiAo78TigQXYMdjrnFjbcbZ62CNEa4wBhjZkaNZ+gTAYAlE0GwHoQsVDjHxtAsYEAdJWAAJD+aFkgaAB1SFUjLsM-gVyiACZriJ+umBI1ED8v5hjKs5O+xgELAAitxkO9MhZFO1kUxw7GYDLRYmTBBy4nCwszJKgZ0cMvGdWLk+resRhyAaLMhohQoTSSsmuzAfghhyDdU61yGmtM6fG5N5ysmzA2CkYaQW1wojlRCBAdhmgFm7IyAgP+pTXC+JEaeXAUkSVtE6N0TAPQDvnemnm47DQTR+URhsbGxt5jhL8niL7oIxgRNu4hIAA

**Comment by Kek5chen** [comment]
You can't really blame me for not detecting short codes though haha, your previous implementation didn't detect those either 😅. Anyways, I'll be adding some keywords and symbols to maybe increase the confidence for these smaller samples.

**Comment by hieunc229** [comment]
Absolutely, the old code was temporary. And as said, unlikely the result can be that short.

I'm hesitant to work on this part because (1) there are lots of cases to cover, and (2) I think it'd be safer to show text, rather than filter out code results. (tbh, I have no idea how to ensure how confident the filter is)

Though, I think this PR could cover common cases.

**Comment by Kek5chen** [comment]
I can test the ability through collecting 100 cases from stackoverflow. That way i can calculate a fairly confident precision. Code that small is mostly of very low quality / very simple. So filtering it out wouldn't be that much of an issue. If people use captain stack to find out how to assign a javascript variable they should rather get autocompleted a youtube tutorial for javascript. *haha*

**Comment by hieunc229** [comment]
That's a good idea. Having 100 cases is a proper number.

Is there anything you want me to do?

> If people use captain stack to find out how to assign a javascript variable they should rather get autocompleted a youtube tutorial for javascript

hahaha, I wouldn't know

**Comment by Kek5chen** [comment]
I'll just be cherry pick some samples from stackoverflow and paste them into my project. no real need for help, thanks though.

**Comment by hieunc229** [comment]
Alrighty then, I'm looking for the update! Feel free to tell me what to do too!

**Comment by Kek5chen** [comment]
not tested in vscode, should be merge ready though.

**Comment by Kek5chen** [comment]
https://pastebin.com/t00wi5SE here are the full test results

**Comment by hieunc229** [comment]
Thanks for this work @Kek5chen. I think the new `isCodeValid` can be a NPM module itself.
By the way, is it really an AI code validation? AI is usually prefer to a program that process data. Not really important though

**Comment by Kek5chen** [comment]
Am i not processing data and generating confidence values from it? I'm getting some input and passing it through some code to output a confidence of how certainly the input was code.

Input -> Hidden layer -> Output.

**Comment by hieunc229** [comment]
You did processing data and generated confidence values, but it was for testing the result. Whereas AI is used as the program to reproduce results.

So you used AI to test the results. The code itself isn't AI.

**Comment by hieunc229** [comment]
Oh wait, are we talking about the program to test the code, or the code?

We're might talking different things here

**Comment by Kek5chen** [comment]
the code itself of course

**Pull request merged**
