### PR TITLE
Adding more site to find code

### PR DESCRIPTION
**Pull request by hieunc229**
@clin1234 @Kek5chen 

I've just added more code sources, now it has **stackoverflow.com**, **gist.github.com**. It's fairly easy to add more sites (will need to add instruction in readme)

A downside of having more code sources is it could take longer for the results to show up.

Any thoughts?

### CODE REVIEW

**Review by clin1234 — APPROVED** [review]

**Review by Kek5chen — CHANGES_REQUESTED** [review]
I just tried to run the code on a fresh installation of VS Code Insiders, I get this error message.

image

**Comment by hieunc229** [comment]
I guess it doesn't find the code in the URL. Let me check

**Comment by Kek5chen** [comment]
Looks promising, will test now

**Review by Kek5chen — APPROVED** [review]
Exactly what i thought the error was. Works now.

**Pull request merged**
